const icons = [
    {id:1,iconName:'canying'},
    {id:2,iconName:'riyong'},
    {id:3,iconName:'xuexi'},
    {id:4,iconName:'kuaidi'},
    {id:5,iconName:'lijin'},
    {id:6,iconName:'licai'},
    {id:7,iconName:'jianzhi'},
    {id:8,iconName:'gongzi'},
    {id:9,iconName:'shejiao'},
    {id:10,iconName:'zhufang'},
    {id:11,iconName:'liwu'},
    {id:12,iconName:'lvxing'},
    {id:13,iconName:'fushi'},
    {id:14,iconName:'shuma'},
    {id:15,iconName:'yanjiu'},
    {id:16,iconName:'jiaotong'},
    {id:17,iconName:'tongxun'},
    {id:18,iconName:'yule'},
    {id:19,iconName:'chongwu'},
    {id:20,iconName:'bangong'},
    {id:21,iconName:'shuiguo'},
    {id:22,iconName:'yundong'},
    {id:23,iconName:'ertong'},
    {id:24,iconName:'laoren'},
    {id:25,iconName:'weixiu'},
    {id:26,iconName:'juanzeng'},
    {id:27,iconName:'caipiao'},
    {id:28,iconName:'meirong'},
    {id:29,iconName:'shucai'},
]

export {icons}